/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#include<stdio.h>

int main(){
  int n=33; 
  unsigned long fib[n];
  fib[0] = 1;
  fib[1] = 1;
  unsigned long sum;
  int i=1;
  for(i=2; i<n; i++){
    fib[i] = fib[i-2]+fib[i-1];
    
    //if the value of the fibonacci number is even, add it to sum:
  }
  int k;
  for(k=0; k<=32; k++){
    if (fib[k]%2==0){
      sum += fib[k];
    }
  }

  printf("%lu\n",sum);
return 0;
}
